# -*- coding: utf-8 -*-
"""IOkadai2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Rcb2dxTY792jIVMKk7rsKDKSET4twyw
"""

# IO31
import time # timer
cnt = 0
# while True: # 無限ループ
while cnt<10: # ループ
  # time.sleep(1) # 1秒毎にループ
  cnt += 1
  if cnt%2:
    print("cnt=",cnt)

