# -*- coding: utf-8 -*-
"""Untitled2-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11wyQVycnnpauAVvugSk5gV20UBgDzquB

#インデント
pythonはインデントが重要って話
* def bmax(a):
* if x>y:
* elif x==y:
* else:
* for i in range(20):
"""

# 練習
def exception3(x,y,z):
  if x==y:
    return z
  elif y==z:
    return x
  else:
    return y
print(exception3(1,2,2))
print(exception3(4,2,4))
print(exception3(9,3,9))
print("=-=-=-=")
# 練習2
def exception9(list9):
  word = list9[0]
  if list9[0] == list9[1] == list9[2]:
    return exception9(list9[3:]);
  else:
    return exception3(list9[0],list9[1],list9[2])
print(exception9([1,2,2,2,2,2,2,2,2]))
print(exception9([4,4,4,4,4,2,4,4,4]))
print(exception9([9,9,9,9,9,9,9,9,3]))

# 練習3
x = -1
if x < 1:
    print('x is less than 1')
elif x < 2:
    print('x is larger than or equal to 1, and less than 2')
elif x < 3:
    print('x is larger than or equal to 2, and less than 3')
else:
    print('x is larger or equal to 3')

### 三項演算子
x = 0
if x >= 0 :
    sign = 'positive or zero'
else:
    sign = 'negative'
print(sign)
print("=-=-=-=-=-=-=-=") # １行に書く三項演算子
sign = 'positive or zero' if x >= 0 else 'negative'
print(sign)

