# -*- coding: utf-8 -*-
"""Untitled1-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X7H4RZhboAY2IX0Iin17BNE793JRraC1
"""

# 仕様分析->プログラミング->テスト->デバッグ

# assert文
# 1-2で既出

"""### エラーの分類
---
#### 構文エラー
・pythonの構文に違反している<br>
・クォート、コロンの書き忘れ<br>
・インデントの崩れ、全角スペースの使用<br>
・=と==の間違い
#### 実行時エラー
・存在しない変数の使用<br>
・グローバル変数とローカル変数の参照ミス<br>
・0で除算<br>
・配列の登録されていないkeyの参照<br>
・存在しないファイルの読み込み
#### 論理エラー
・いわゆる「バグ」。プログラムは実行できるが仕様と違う
"""