# -*- coding: utf-8 -*-
"""Untitled1-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12tb1tBJf8_biR3SQhuj2rAUI5IuYMuLt
"""

int(2.8)

int(-2.7)

float(3)

17 - 17 // 3 * 3 # 計算の優先順位

4 ** 3 ** 2 # 右から優先される

import math
math.sqrt(5)

math.pi

math.cos(0)

math.sin(math.pi/4) * 2 # = 1/sqrt(2) * 2

(1+math.sqrt(5))/2 # 黄金比