# -*- coding: utf-8 -*-
"""Untitled1-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j_2B4N2PzsoKZGdMS0nyq0oh1y0iHgD2
"""

# 条件分岐
def bmax(a,b):
    if a > b:
      return a
    return b
bmax(3,5)

# 組み込み関数が存在する
max(3,5)

print(not 3 > 5)
print(1==1 or 3!=3)
print(1==1 and 3!=3)

# 連続して用いることも可能
print(3<4<5)
print(3<9==6)

def absolute(x):
  if x<0:
    return -x
  return x
print(absolute(3))
print(absolute(-5))
print(absolute(0))

def sign(x):
  if x<0:
    return -1
  if x==0:
    return 0
  return 1

# 真理値を返す関数
def is_even(x):
  return x%2 == 0
print(is_even(91))
print(is_even(56))

print(None)
if None: print("ok")
else: print("ng")

if 0: print("0==True")
else: print("0==False")

if 1: print("1==True")
else: print("1==False")

# 再帰
# フィボナッチ数列
def fib(n):
  if n < 2: return n
  else: return fib(n-1) + fib(n-2)
print(fib(9))

