# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I6iX1eTkn9TAvDXEEhtBu0sZy7lMK52J
"""

1+1

10/3

while True:
  pass

2**4

7//2

7%2

